services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASS='' # samakan dengan database
      - DB_NAME=sistem_karyawan
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php


  php:
    build:
      context: php/
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASS='' # samakan dengan database
      - DB_NAME=sistem_karyawan

  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes # Mengizinkan password kosong untuk root, "no" jika ingin mengatur password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '' # isi password kosong sesuai keinginan
      MYSQL_DATABASE: sistem_karyawan
    volumes:
      - emplorapro_db:/var/lib/mysql

  phpmyadmin:
    container_name: PhpMyAdmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: '' # samakan dengan database
    depends_on:
      - database

volumes:
  emplorapro_db:
    driver: local