services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=thunderst0rm
      - DB_NAME=database
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - database

  php:
    build:
      context: php/
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=thunderst0rm
      - DB_NAME=database

  database:
    container_name: mysql-server
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thunderst0rm
      MYSQL_DATABASE: sistem_karyawan
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    container_name: PhpMyAdmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: thunderst0rm
    depends_on:
      - database
